version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    choco install -y InnoSetup
    set PATH="C:\Program Files\7-Zip";"C:\Program Files (x86)\Inno Setup 5";%PATH%
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "Package"
build:
  verbosity: minimal
artifacts:
- path: artifacts\*.zip
- path: artifacts\*.exe
- path: artifacts\GUI\Release\Win32\*.exe
- path: artifacts\GUI\Release\x64\*.exe
- path: artifacts\CLI\Release\Win32\*.exe
- path: artifacts\CLI\Release\x64\*.exe
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/b2ef66b4751356ad6489
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
