version: '{build}'
image: Visual Studio 2017
install:
- choco install -y InnoSetup
- set PATH="C:\Program Files\7-Zip";"C:\Program Files (x86)\Inno Setup 5";%PATH%
before_build:
- git submodule update --init
build_script:
- ps: .\build.ps1 -Target "Package"
test: off
artifacts:
- path: artifacts\*.zip
- path: artifacts\*.exe
- path: artifacts\Release\Win32\*.exe
- path: artifacts\Release\x64\*.exe
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/f2ddd523fe04ad255028
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
